name: Get Info Box
description: Get announcments and vacations in an info box if necessary

inputs:
  announcment:
    required: true
  vacation-from:
    required: true
  vacation-to:
    required: true

outputs:
  info-box-markup:
    description: The markup of the info box if present
    value: ${{ steps.get-info-box.outputs.info-box-markup }}

runs:
  using: "composite"
  steps:

    - name: Setup node
      uses: actions/setup-node@v6

    - name: Run script
      id: get-info-box
      shell: bash
      env:
        ANNOUNCMENT: ${{ inputs.announcment }}
        VACATION_FROM: ${{ inputs.vacation-from }}
        VACATION_TO: ${{ inputs.vacation-to }}
      run: |
        INFO_BOX_MARKUP=node ./.github/scripts/get-info-box.js
        echo "info-box-markup=$INFO_BOX_MARKUP" >> "$GITHUB_OUTPUT"
