name: Get Info Box
description: Get announcments and vacations in an info box if necessary

inputs:
  announcment:
    required: true
  vacation-from:
    required: true
  vacation-to:
    required: true

outputs:
  info-box-markup:
    description: The markup of the info box if present

runs:
  using: "composite"
  steps:

    - name: Setup node
      uses: actions/setup-node@v6

    - name: Run script
      shell: bash
      env:
        ANNOUNCMENT: ${{ inputs.announcment }}
        VACATION_FROM: ${{ inputs.vacation-from }}
        VACATION_TO: ${{ inputs.vacation-to }}
      run: echo "info-box-markup=$(node ./.github/actions/get-info-box/index.js)" >> "$GITHUB_OUTPUT"
