name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: sudo apt-get install imagemagick

      - name: Compress images
        working-directory: src
        run: |
          find ./img             -name 'deko*.webp'           -exec mogrify -resize 160x160   -quality 20\> {} \;
          find ./img             -name 'gasthaus-gundel.webp' -exec mogrify -resize 1280x1280 -quality 35\> {} \;
          find ./img/speisekarte -name '*.webp'               -exec mogrify -resize 1280x1280 -quality 35\> {} \;

      - name: Generate info box
        uses: ./.github/actions/get-info-box
        id: get-info-box
        with:
          announcment: ${{ vars.ANNOUNCMENT}}
          vacation-from: ${{ vars.VACATION_FROM}}
          vacation-to: ${{ vars.VACATION_TO}}

      - name: Apply info box
        if: ${{ steps.get-info-box.outputs.info-box-markup != '' }}
        working-directory: src
        env:
          INFO_BOX_MARKUP: ${{ steps.get-info-box.outputs.info-box-markup }}
        run: sed -i "s|\[INFO_BOX\]|$INFO_BOX_MARKUP|g" index.html

      - name: Upload bundle
        uses: actions/upload-artifact@v6
        with:
          name: bundle
          path: src
            
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Install dependencies
        run: sudo apt-get install lftp

      - name: Download bundle
        uses: actions/download-artifact@v7
        with:
          name: bundle
          path: .

      - name: Pull .well-known
        continue-on-error: true
        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; mirror .well-known ./; quit;" ${{ secrets.FTP_URL }}

      - name: Deploy new bundle
        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; mirror --reverse --delete --use-cache --verbose --allow-suid --no-umask --parallel=10; quit;" ${{ secrets.FTP_URL }}