name: Config

on:
  workflow_dispatch:
    inputs:
      ANNOUNCMENT:
        required: false
        description: Optionaler Ankündigungstext
        type: string

      VACATION_FROM:
        required: false
        description: Erster Urlaubs-Tag in ISO 8601 (JJJJ-MM-TT)
        type: string

      VACATION_TO:
        required: false
        description: Letzter Urlaubs-Tag in ISO 8601 (JJJJ-MM-TT)
        type: string

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  configure:
    name: Apply config
    runs-on: ubuntu-slim
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Checkout
        uses: actions/checkout@v7

      - name: Validate inputs
        run: exit 0;

      - name: Old variables
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh variable list

      - name: Update variables
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
        
          if [ -n "${{ inputs.ANNOUNCMENT}}" ]; then
            gh variable set ANNOUNCMENT --body "${{ inputs.ANNOUNCMENT }}"
          else
            gh variable delete ANNOUNCMENT || true
          fi
          
          if [ -n "${{ inputs.VACATION_FROM}}" ]; then
            gh variable set VACATION_FROM --body "${{ inputs.VACATION_FROM }}"
          else
            gh variable delete VACATION_FROM || true
          fi

          if [ -n "${{ inputs.VACATION_TO}}" ]; then
            gh variable set VACATION_TO --body "${{ inputs.VACATION_TO }}"
          else
            gh variable delete VACATION_TO || true
          fi

      - name: New variables
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh variable list

      - name: Dispatch deployment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run ci.yml
