name: Config

on:
  workflow_dispatch:
    inputs:
      ANNOUNCMENT:
        required: false
        description: Any prosa announcment
        type: string

      VACATION_FROM:
        required: false
        description: First day closed in ISO 8601 (yyyy-mm-dd)
        type: string

      VACATION_TO:
        required: false
        description: Last day closed in ISO 8601 (yyyy-mm-dd)
        type: string

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  set-vacation:
    name: Set vacation
    runs-on: ubuntu-slim
    if: github.ref == 'refs/heads/master'
    steps:

      - name: Validate inputs
        run: exit 0;

      - name: Old variables
        run: gh variable list

      - name: Update variables
        run: |
          gh variable set ANNOUNCMENT --body "${{ inputs.ANNOUNCMENT }}"
          gh variable set VACATION_FROM --body "${{ inputs.VACATION_FROM }}"
          gh variable set VACATION_TO --body "${{ inputs.VACATION_TO }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: New variables
        run: gh variable list

      - name: Dispatch deployment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run ci.yml
